export const countries = [
{name: "Uluslararası", flag: "uluslararasi.svg"},
{name: "Afganistan", flag: "afganistan.svg"},
{name: "Åland Adaları", flag: "aland-adalari.svg"},
{name: "Almanya", flag: "almanya.svg"},
{name: "Amerika Birleşik Devletleri", flag: "amerika-birlesik-devletleri.svg"},
{name: "Amerikan Samoası", flag: "amerikan-samoa.svg"},
{name: "Andorra", flag: "andorra.svg"},
{name: "Angola", flag: "angola.svg"},
{name: "Anguilla", flag: "anguilla.svg"},
{name: "Antigua ve Barbuda", flag: "antigua-ve-barbuda.svg"},
{name: "Arjantin", flag: "arjantin.svg"},
{name: "Arnavutluk", flag: "arnavutluk.svg"},
{name: "Aruba", flag: "aruba.svg"},
{name: "Avustralya", flag: "avustralya.svg"},
{name: "Avusturya", flag: "avusturya.svg"},
{name: "Azerbaycan", flag: "azerbaycan.svg"},
{name: "Aziz Barthélemy", flag: "aziz-barthelemy.svg"},
{name: "Aziz Helena", flag: "aziz-helena.svg"},
{name: "Bahamalar", flag: "bahamalar.svg"},
{name: "Bahreyn", flag: "bahreyn.svg"},
{name: "Bangladeş", flag: "banglades.svg"},
{name: "Barbados", flag: "barbados.svg"},
{name: "Batı Sahra", flag: "bati-sahra.svg"},
{name: "Belçika", flag: "belcika.svg"},
{name: "Belize", flag: "belize.svg"},
{name: "Benin", flag: "benin.svg"},
{name: "Bermuda", flag: "bermuda.svg"},
{name: "Beyaz Rusya", flag: "beyaz-rusya.svg"},
{name: "Birleşik Arap Emirlikleri", flag: "birlesik-arap-emirlikleri.svg"},
{name: "Bolivya", flag: "bolivya.svg"},
{name: "Bonaire, Sint Eustatius ve Saba", flag: "bonaire-sint-eustatius-ve-saba.svg"},
{name: "Bosna Hersek", flag: "bosna-hersek.svg"},
{name: "Botsvana", flag: "botsvana.svg"},
{name: "Brezilya", flag: "brezilya.svg"},
{name: "Brunei Darussalam", flag: "brunei-darussalam.svg"},
{name: "Bulgaristan", flag: "bulgaristan.svg"},
{name: "Burkina Faso", flag: "burkina-faso.svg"},
{name: "Burundi", flag: "burundi.svg"},
{name: "Butan", flag: "butan.svg"},
{name: "Cayman Adaları", flag: "cayman-adalari.svg"},
{name: "Cebelitarık", flag: "cebelitarik.svg"},
{name: "Cezayir", flag: "cezayir.svg"},
{name: "Christmas Adası", flag: "christmas-adasi.svg"},
{name: "Cibuti", flag: "cibuti.svg"},
{name: "Cocos (Keeling) Adaları", flag: "cocos-keeling-adalari.svg"},
{name: "Cook Adaları", flag: "cook-adalari.svg"},
{name: "Curaçao", flag: "curacao.svg"},
{name: "Çad", flag: "cad.svg"},
{name: "Çek Cumhuriyeti", flag: "cek-cumhuriyeti.svg"},
{name: "Çin", flag: "cin.svg"},
{name: "Danimarka", flag: "danimarka.svg"},
{name: "Doğu Timor", flag: "dogu-timor.svg"},
{name: "Dominik Cumhuriyeti", flag: "dominik-cumhuriyeti.svg"},
{name: "Dominika", flag: "dominika.svg"},
{name: "Ekvador", flag: "ekvador.svg"},
{name: "Ekvator Ginesi", flag: "ekvator-ginesi.svg"},
{name: "El Salvador", flag: "el-salvador.svg"},
{name: "Endonezya", flag: "endonezya.svg"},
{name: "Eritre", flag: "eritre.svg"},
{name: "Ermenistan", flag: "ermenistan.svg"},
{name: "Estonya", flag: "estonya.svg"},
{name: "Etiyopya", flag: "etiyopya.svg"},
{name: "Falkland Adaları", flag: "falkland-adalari.svg"},
{name: "Faroe Adaları", flag: "faroe-adalari.svg"},
{name: "Fas", flag: "fas.svg"},
{name: "Fiji", flag: "fiji.svg"},
{name: "Fildişi Sahili", flag: "fildisi-sahili.svg"},
{name: "Filipinler", flag: "filipinler.svg"},
{name: "Filistin", flag: "filistin.svg"},
{name: "Finlandiya", flag: "finlandiya.svg"},
{name: "Fransa", flag: "fransa.svg"},
{name: "Fransız Guyanası", flag: "fransiz-guyanasi.svg"},
{name: "Fransız Polinezyası", flag: "fransiz-polinezyasi.svg"},
{name: "Gabon", flag: "gabon.svg"},
{name: "Gambiya", flag: "gambiya.svg"},
{name: "Gana", flag: "gana.svg"},
{name: "Gine", flag: "gine.svg"},
{name: "Gine-Bissau", flag: "gine-bissau.svg"},
{name: "Grenada", flag: "grenada.svg"},
{name: "Grönland", flag: "gronland.svg"},
{name: "Guadeloupe", flag: "guadeloupe.svg"},
{name: "Guam", flag: "guam.svg"},
{name: "Guatemala", flag: "guatemala.svg"},
{name: "Guernsey", flag: "guernsey.svg"},
{name: "Guyana", flag: "guyana.svg"},
{name: "Güney Afrika", flag: "guney-afrika.svg"},
{name: "Güney Kore", flag: "guney-kore.svg"},
{name: "Güney Sudan", flag: "guney-sudan.svg"},
{name: "Gürcistan", flag: "gurcistan.svg"},
{name: "Haiti", flag: "haiti.svg"},
{name: "Hırvatistan", flag: "hirvatistan.svg"},
{name: "Hindistan", flag: "hindistan.svg"},
{name: "Hollanda", flag: "hollanda.svg"},
{name: "Holy See (Vatikan Şehir Devleti)", flag: "holy-see-vatikan-sehir-devleti.svg"},
{name: "Honduras", flag: "honduras.svg"},
{name: "Hong Kong", flag: "hong-kong.svg"},
{name: "Irak", flag: "irak.svg"},
{name: "İngiliz Hint Okyanusu Bölgesi", flag: "ingiliz-hint-okeyanusu-bolgesi.svg"},
{name: "İngiltere", flag: "ingiltere.svg"},
{name: "İran", flag: "iran.svg"},
{name: "İrlanda", flag: "irlanda.svg"},
{name: "İspanya", flag: "ispanya.svg"},
{name: "İsrail", flag: "israil.svg"},
{name: "İsveç", flag: "isvec.svg"},
{name: "İsviçre", flag: "isvicre.svg"},
{name: "İtalya", flag: "italya.svg"},
{name: "İzlanda", flag: "izlanda.svg"},
{name: "Jamaika", flag: "jamaika.svg"},
{name: "Japonya", flag: "japonya.svg"},
{name: "Jersey", flag: "jersey.svg"},
{name: "Kamboçya", flag: "kamboçya.svg"},
{name: "Kamerun", flag: "kamerun.svg"},
{name: "Kanada", flag: "kanada.svg"},
{name: "Karadağ", flag: "karadag.svg"},
{name: "Katar", flag: "katar.svg"},
{name: "Kazakistan", flag: "kazakistan.svg"},
{name: "Kenya", flag: "kenya.svg"},
{name: "Kıbrıs", flag: "kibris.svg"},
{name: "Kırgızistan", flag: "kirgizistan.svg"},
{name: "Kiribati", flag: "kiribati.svg"},
{name: "Kolombiya", flag: "kolombiya.svg"},
{name: "Komorlar", flag: "komorlar.svg"},
{name: "Kongo", flag: "kongo.svg"},
{name: "Kongo, Demokratik Cumhuriyeti", flag: "kongo-demokratik-cumhuriyeti.svg"},
{name: "Kosova", flag: "kosova.svg"},
{name: "Kosta Rika", flag: "kosta-rika.svg"},
{name: "Kuveyt", flag: "kuveyt.svg"},
{name: "Kuzey Kore", flag: "kuzey-kore.svg"},
{name: "Kuzey Makedonya", flag: "kuzey-makedonya.svg"},
{name: "Kuzey Mariana Adaları", flag: "kuzey-mariana-adalari.svg"},
{name: "Küba", flag: "kuba.svg"},
{name: "Laos", flag: "laos.svg"},
{name: "Lesotho", flag: "lesotho.svg"},
{name: "Letonya", flag: "letonya.svg"},
{name: "Liberya", flag: "liberya.svg"},
{name: "Libya", flag: "libya.svg"},
{name: "Lihtenştayn", flag: "lihtenstayn.svg"},
{name: "Litvanya", flag: "litvanya.svg"},
{name: "Lübnan", flag: "lubnan.svg"},
{name: "Lüksemburg", flag: "luksemburg.svg"},
{name: "Macaristan", flag: "macaristan.svg"},
{name: "Madagaskar", flag: "madagaskar.svg"},
{name: "Makao", flag: "makao.svg"},
{name: "Malavi", flag: "malavi.svg"},
{name: "Maldivler", flag: "maldivler.svg"},
{name: "Malezya", flag: "malezya.svg"},
{name: "Mali", flag: "mali.svg"},
{name: "Malta", flag: "malta.svg"},
{name: "Man Adası", flag: "man-adasi.svg"},
{name: "Marshall Adaları", flag: "marshall-adalari.svg"},
{name: "Martinik", flag: "martinik.svg"},
{name: "Mauritius", flag: "mauritius.svg"},
{name: "Mayotte", flag: "mayotte.svg"},
{name: "Meksika", flag: "meksika.svg"},
{name: "Mısır", flag: "misir.svg"},
{name: "Mikronezya Federal Devletleri", flag: "mikronezya_federal_devletleri.svg"},
{name: "Moğolistan", flag: "mogolistan.svg"},
{name: "Moldova", flag: "moldova.svg"},
{name: "Monako", flag: "monako.svg"},
{name: "Montserrat", flag: "montserrat.svg"},
{name: "Moritanya", flag: "moritanya.svg"},
{name: "Mozambik", flag: "mozambik.svg"},
{name: "Myanmar", flag: "myanmar.svg"},
{name: "Namibya", flag: "namibya.svg"},
{name: "Nauru", flag: "nauru.svg"},
{name: "Nepal", flag: "nepal.svg"},
{name: "Nijer", flag: "nijer.svg"},
{name: "Nijerya", flag: "nijerya.svg"},
{name: "Nikaragua", flag: "nikaragua.svg"},
{name: "Niue", flag: "niue.svg"},
{name: "Norfolk Adası", flag: "norfolk_adasi.svg"},
{name: "Norveç", flag: "norvec.svg"},
{name: "Orta Afrika Cumhuriyeti", flag: "orta_afrika_cumhuriyeti.svg"},
{name: "Özbekistan", flag: "ozbekistan.svg"},
{name: "Pakistan", flag: "pakistan.svg"},
{name: "Palau", flag: "palau.svg"},
{name: "Panama", flag: "panama.svg"},
{name: "Papua Yeni Gine", flag: "papua_yeni_gine.svg"},
{name: "Paraguay", flag: "paraguay.svg"},
{name: "Peru", flag: "peru.svg"},
{name: "Polonya", flag: "polonya.svg"},
{name: "Portekiz", flag: "portekiz.svg"},
{name: "Porto Riko", flag: "porto_riko.svg"},
{name: "Romanya", flag: "romanya.svg"},
{name: "Ruanda", flag: "ruanda.svg"},
{name: "Rusya", flag: "rusya.svg"},
{name: "Saint Kitts ve Nevis", flag: "saint_kitts_ve_nevis.svg"},
{name: "Saint Lucia", flag: "saint_lucia.svg"},
{name: "Saint Martin (Fransız Bölgesi)", flag: "saint_martin_fransiz_bolgesi.svg"},
{name: "Saint Pierre ve Miquelon", flag: "saint_pierre_ve_miquelon.svg"},
{name: "Saint Vincent ve Grenadinler", flag: "saint_vincent_ve_grenadinler.svg"},
{name: "Samoa", flag: "samoa.svg"},
{name: "San Marino", flag: "san_marino.svg"},
{name: "Sao Tome ve Principe", flag: "sao_tome_ve_principe.svg"},
{name: "Senegal", flag: "senegal.svg"},
{name: "Seyşeller", flag: "seyseller.svg"},
{name: "Sırbistan", flag: "sirbistan.svg"},
{name: "Sierra Leone", flag: "sierra_leone.svg"},
{name: "Singapur", flag: "singapur.svg"},
{name: "Sint Maarten", flag: "sint_maarten.svg"},
{name: "Slovakya", flag: "slovakya.svg"},
{name: "Slovenya", flag: "slovenya.svg"},
{name: "Solomon Adaları", flag: "solomon_adalari.svg"},
{name: "Somali", flag: "somali.svg"},
{name: "Sri Lanka", flag: "sri_lanka.svg"},
{name: "Sudan", flag: "sudan.svg"},
{name: "Surinam", flag: "surinam.svg"},
{name: "Suriye", flag: "suriye.svg"},
{name: "Suudi Arabistan", flag: "suudi_arabistan.svg"},
{name: "Svalbard ve Jan Mayen", flag: "svalbard_ve_jan_mayen.svg"},
{name: "Svaziland", flag: "svaziland.svg"},
{name: "Şili", flag: "sili.svg"},
{name: "Tacikistan", flag: "tacikistan.svg"},
{name: "Tanzanya", flag: "tanzanya.svg"},
{name: "Tayland", flag: "tayland.svg"},
{name: "Tayvan", flag: "tayvan.svg"},
{name: "Togo", flag: "togo.svg"},
{name: "Tokelau", flag: "tokelau.svg"},
{name: "Tonga", flag: "tonga.svg"},
{name: "Trinidad ve Tobago", flag: "trinidad_ve_tobago.svg"},
{name: "Tristan da Cunha", flag: "tristan_da_cunha.svg"},
{name: "Tunus", flag: "tunus.svg"},
{name: "Turks ve Caicos Adaları", flag: "turks_ve_caicos_adalari.svg"},
{name: "Tuvalu", flag: "tuvalu.svg"},
{name: "Türkiye", flag: "turkiye.svg"},
{name: "Türkmenistan", flag: "turkmenistan.svg"},
{name: "Uganda", flag: "uganda.svg"},
{name: "Ukrayna", flag: "ukrayna.svg"},
{name: "Umman", flag: "umman.svg"},
{name: "Uruguay", flag: "uruguay.svg"},
{name: "Ürdün", flag: "urdun.svg"},
{name: "Vanuatu", flag: "vanuatu.svg"},
{name: "Venezuela", flag: "venezuela.svg"},
{name: "Vietnam", flag: "vietnam.svg"},
{name: "Virgin Adaları, ABD", flag: "virgin_adalari_abd.svg"},
{name: "Virgin Adaları, İngiliz", flag: "virgin_adalari_ingiliz.svg"},
{name: "Wallis ve Futuna", flag: "wallis_ve_futuna.svg"},
{name: "Yemen", flag: "yemen.svg"},
{name: "Yeni Kaledonya", flag: "yeni_kaledonya.svg"},
{name: "Yeni Zelanda", flag: "yeni_zelanda.svg"},
{name: "Yeniden Birleşme", flag: "yeniden_birlesme.svg"},
{name: "Yeşil Burun Adaları", flag: "yesil_burun_adalari.svg"},
{name: "Yunanistan", flag: "yunanistan.svg"},
{name: "Yükseliş Adası", flag: "yukselis_adasi.svg"},
{name: "Zambiya", flag: "zambiya.svg"},
{name: "Zimbabve", flag: "zimbabve.svg"}
]