export interface ProfileDto {
    id: number,
    firstname: string,
    lastname: string,
    phone:string,
    birthdate: Date,
    nationalIdentity : string,
    email: string,
    city:string,
    country:string,
    district:string,
    addressDetail:string,
    aboutMe:string,
    status: boolean,
}
